import { app, BrowserWindow, dialog, ipcMain } from 'electron';
// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require('electron-squirrel-startup')) {
  app.quit();
}

// IPC: print or save ticket as PDF (register early)
ipcMain.handle('kiosk:print-or-save', async (_event, args: { html: string }) => {
  const tempWin = new BrowserWindow({
    show: false,
    webPreferences: { offscreen: false },
  });
  try {
    await tempWin.loadURL('data:text/html;charset=utf-8,' + encodeURIComponent(args.html));
    let printed = false;
    // Prefer async API if available
    const getPrintersAsync = (tempWin.webContents as any).getPrintersAsync?.bind(tempWin.webContents);
    try {
      const printers = getPrintersAsync ? await getPrintersAsync() : (tempWin.webContents as any).getPrinters?.() || [];
      const defaultPrinter = Array.isArray(printers) ? printers.find((p: any) => p.isDefault) : undefined;
      if (defaultPrinter) {
        await tempWin.webContents.print({ silent: true });
        printed = true;
      }
    } catch (e) {
      // ignore and fall back to PDF
    }
    if (!printed) {
      const pdfBuffer = await tempWin.webContents.printToPDF({ printBackground: true });
      const downloads = app.getPath('downloads');
      const filePath = `${downloads}/ticket-${Date.now()}.pdf`;
      const fs = require('fs');
      await fs.promises.writeFile(filePath, pdfBuffer);
    }
  } catch (e) {
    console.error('print-or-save failed', e);
    try {
      const pdfBuffer = await tempWin.webContents.printToPDF({ printBackground: true });
      const downloads = app.getPath('downloads');
      const fallbackPath = `${downloads}/ticket-${Date.now()}.pdf`;
      const fs = require('fs');
      await fs.promises.writeFile(fallbackPath, pdfBuffer);
    } catch (e2) {
      console.error('fallback save failed', e2);
    }
  } finally {
    tempWin.destroy();
  }
});

const createWindow = (): void => {
  // Create the browser window.
  const mainWindow = new BrowserWindow({
    height: 800,
    width: 1200,
    webPreferences: {
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
      nodeIntegration: false,
      contextIsolation: true,
      webSecurity: true, // Enable web security with proper CSP
    },
  });

  // and load the index.html of the app.
  mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);

  // Open the DevTools.
  mainWindow.webContents.openDevTools();
};

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.on('ready', createWindow);

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    app.quit();
  }
});

app.on('activate', () => {
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow();
  }
});

// In this file you can include the rest of your app's specific main process
// code. You can also put them in separate files and import them here.
